### ISSUE TITLE
O background não é contínuo entre mapa e benefícios

### ISSUE THREAD

**Issue by karengiovanna** [karengiovanna/Barbearia-Alura#1]
```CSS
.mapa{
    padding: 3em 0;
    background:linear-gradient(#FFFF,#9BB7D4,#FFFF);
}
```

Inseri um background gradiente na classe mapa e gostaria de fazer o mesmo com a classe benefícios que fica abaixo. Porém um fundo não é contínuo do outro, há um elemento vazio entre os dois que não faz parte do background
